server:
  # 服务器端口
  port: 8888

mybatis:
  # 扫描mapper.xml
  mapper-locations: classpath*:mapper/*.xml
  # 扫描实体类
  type-aliases-package: com.skotori.sunzboot.module.sys.model
  # 配置驼峰转换
  configuration:
    map-underscore-to-camel-case: true

# 打印sql语句
logging:
  level:
    # mapper所在包
    com.skotori.sunzboot.module.sys.mapper: debug

# pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring:
  profiles:
    #选择数据库配置
    active: dev
  # jackson
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置空如何序列化
    default-property-inclusion: non_empty
    serialization:
      # 格式化输出
      INDENT_OUTPUT: true
      # 忽略无法转换的对象
      FAIL_ON_EMPTY_BEANS: true
    deserialization:
      # 允许对象忽略json中不存在的属性
      FAIL_ON_UNKNOWN_PROPERTIES: false
    parser:
      # 允许出现特殊字符和转义符
      ALLOW_UNQUOTED_CONTROL_CHARS: true
      # 允许出现单引号
      ALLOW_SINGLE_QUOTES: true

---

#dev开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sunz_boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置获取连接等待超时的时间
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
